##### 导入pandas并命名为pd

In [1]:
import pandas as pd

##### 创建Series名为name，包含字符串元素"小陈"，"小李"，"小王"，"小张"，"小赵"，"小周",标签为"001"，"002"，"003"，"004"，"005"，"006".  
创建Series 名为gender，包含字符串元素"女"，"女"，"男"，"男"，"女"，"男"，标签为"006"，"005"，"004"，"003"，"002"，"001".  
创建Series 名为height，包含浮点元素172.5,168.0,178.2,181.3,161.7,标签为"001"，"002"，"003"，"004"，"005"。

In [6]:
name=pd.Series(["小陈","小李","小王","小张","小赵","小周"],index=["001","002","003","004","005","006"])
gender=pd.Series(["女","女","男","男","女","男"],index=["006","005","004","003","002","001"])
height=pd.Series([172.5,168.0,178.2,181.3,161.7],index=["001","002","003","004","005"])

##### 创建DataFrame名为student，包含列名：姓名、性别、身高；数据分别对应创建好的三个Series：name、gender以及height。输出student。

In [21]:
students = pd.DataFrame({"姓名":name,"性别":gender,"身高":height})
students

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7
006  小周  女    NaN

##### 打印student所有的索引和列名。

In [18]:
print(students.index)
print(students.columns)

Index(['001', '002', '003', '004', '005', '006'], dtype='str')
Index(['姓名', '性别', '身高'], dtype='str')

##### 输出把students的行和列转置后的结果。

In [20]:
students.T

      001    002    003    004    005  006
姓名     小陈     小李     小王     小张     小赵   小周
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN

##### 输出students的身高列

In [25]:
students["身高"]

001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64

##### 输出students的性别和身高列

In [34]:
students[["性别","身高"]]

    性别     身高
001  男  172.5
002  女  168.0
003  男  178.2
004  男  181.3
005  女  161.7
006  女    NaN

##### 输出students索引为003的行

In [41]:
students.loc["003"]

姓名       小王
性别        男
身高    178.2
Name: 003, dtype: object

##### 输出索引为003、004、005的行

In [44]:
students.loc["003":"005"]

     姓名 性别     身高
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

##### 输出students里索引为005的身高

In [60]:
students.loc["005","身高"]

np.float64(161.7)

##### 输出students索引为003,005的数据的姓名和身高

In [67]:
students.loc[["003","005"],["姓名","身高"]]

     姓名     身高
003  小王  178.2
005  小赵  161.7

##### 输出所有索引为003,005的变量

In [68]:
students.loc[["003","005"]]

     姓名 性别     身高
003  小王  男  178.2
005  小赵  女  161.7

##### 输出students里身高大于165的女性

In [84]:
students[(students["身高"] > 165) & (students["性别"] == "女性")]

Empty DataFrame
Columns: [姓名, 性别, 身高]
Index: []

##### 通过head方法，输出students前五行数据

In [62]:
students.head()

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7