In [1]:
import pandas as pd

##### 创建一个名为students的DataFrame，包含数据如下：  
{"001":{"姓名":"小陈","考试1":85,"考试2":92,"考试3":92}，"002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94}，"003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89}，"004":{"姓名":"小张","考试1":79,"考试2":89,"考试3":95}，"005":{"姓名":"小赵","考试1":96,"考试2":91,"考试3":91}，"006":{"姓名":"小周","考试1":81,"考试2":89,"考试3":92}}  
要求索引为学号（001,、002等），列名为姓名、考试1、考试2、考试3，并输出创建好的DataFrame。

In [47]:
student_data={"001":{"姓名":"小陈","考试1":85,"考试2":92,"考试3":92},"002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94},"003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89},"004":{"姓名":"小张","考试1":79,"考试2":89,"考试3":95},"005":{"姓名":"小赵","考试1":96,"考试2":91,"考试3":91},"006":{"姓名":"小周","考试1":81,"考试2":89,"考试3":92}}
students=pd.DataFrame(student_data).T
students

     姓名 考试1 考试2 考试3
001  小陈  85  92  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

##### 给students增加一列考试4，数据依次为[72,69,79,83,82,76]

In [48]:
students["考试4"]=[72,69,79,83,82,76]
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  92  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76

##### 给students添加一行，索引为007，数据为:"小杨",79,82,81,69.

In [49]:
students.loc["007"]=["小杨",79,82,81,69]
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  92  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

##### 输出students删除索引为006、007的结果，但不要改变students本身。

In [52]:
students.drop(["006","007"])

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  92  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82

##### 输出students删除列名为"考试2","考试4"的结果，但不要改变students本身。

In [54]:
students.drop(["考试2","考试4"],axis=1)
s

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  92  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

##### 创建一个Series bonus，包含的值和值对应的索引分别为:{"考试1":2,"考试2":3,"考试3":4,"考试4":5}。输出这个Series与students里所有分数列相加后的结果，但不用更新students::students[["考试1","考试2","考试3","考试4"]].add(bonus) 所得结果和以下运算一样。

In [41]:
bonus = pd.Series([2,3,4,5],index=["考试1","考试2","考试3","考试4"])
students[["考试1","考试2","考试3","考试4"]]+bonus

KeyError: "None of [Index(['考试1', '考试2', '考试3', '考试4'], dtype='str')] are in the [index]"

##### 更新students的考试4，让每项数据值增加10，并输出更新后的结果。

In [46]:
students["考试4"] = students["考试4"]+ 10
students

KeyError: '考试4'